<!-- footer starts -->
<div class="splash-bg"></div>
<!-- footer ends -->

<!-- Road block pop up starts -->
<div id="rate-our-app" class="white-popup-block mfp-hide">
	<div class="rate-our-app-img"><img src="resources/images/rate-our-app.jpg" alt=""></div>
	<h4>Rate Our App</h4>
	<p>If you enjoying using CKGS App, would you mind taking a moment to rate it? It won’t take more than a minute. Thanks for your support!</p>
	<a href="#" class="btn">Rate Now</a>
	<a href="#" class="btn gray-btn">Maybe Later</a>
	<a href="#" class="btn gray-btn mfp-close">No Thanks</a>
</div>

<script  src="resources/js/plugins.js"></script>
<script src="resources/js/main.js"></script> 
<script src="resources/js/form-elements.js"></script>
<script>
$('.popup-inline').magnificPopup({
	type: 'inline',
	fixedContentPos: false,
	fixedBgPos: true,
	overflowY: 'auto',
	closeBtnInside: true,
	preloader: false,
	removalDelay: 300,
	mainClass: 'my-mfp-zoom-in'
});
</script>
<!-- Road block pop up starts -->
