<meta name="viewport" content="width=device-width, initial-scale=1; maximum-scale=1">

<!-- Header Css and Script :: starts -->
<link href="resources/css/bootstrap.min.css" rel="stylesheet"><!-- Bootstrap core CSS -->
<link href="resources/css/plugin.css" rel="stylesheet" type="text/css" media="all" /><!-- icons -->

<!-- Custom styles for this template -->
<link href="resources/css/style.css" rel="stylesheet">
<link href="resources/css/media.css" rel="stylesheet">

<!--[if lt IE 9]>
<script src="resources/js/ie/respond.min.js"></script>
<![endif]-->

<script type="text/javascript" src="resources/js/jquery.min.js"></script>
<script type="text/javascript" src="resources/js/modernizr-2.6.2.min.js"></script>
<!-- Header Css and Script :: starts -->
