<header class="master-header">
    <!-- Navigation bar starts -->
		<button class="app-btns toggleMenu"><i></i></button>
		<div class="navbar sidenav">
			<nav class="">
				<ul class="nav">
					<li class="nav-track-application-status"><a href="track-application-status.html"><i class="fa-file-text-o"></i> <span>Track Application Status</span></a></li>
					<li class="nav-track-shipping-status"><a href="track-shipping-status.html"><i class="fa-envelope-o"></i> <span>Track Shipping Status</span></a></li>
					<li class="nav-feedback"><a href="feedback.html"><i class="fa-comment-o"></i> <span>Feedback</span></a></li>
					<li class="nav-complaint"><a href="complaint.html"><i class="fa-edit"></i> <span>Complaint</span></a></li>
					<li class="nav-holiday-list"><a href="holiday-list.html"><i class="fa-calendar-o"></i> <span>Holiday List</span></a></li>
					<li class="nav-faqs"><a href="faqs.html"><i class="fa-question"></i> <span>FAQs</span></a></li>
					<li class="nav-ckgs-spplication-centers"><a href="ckgs-application-center.html"><i class="fa-map-marker"></i> <span>CKGS Application Centers</span></a></li>
					<li class="nav-terms-conditions"><a href="terms-and-conditions.html"><i class="fa-file-text-o"></i> <span>Terms &amp; Conditions</span></a></li>
					<li class="nav-privacy-policy"><a href="privacy-policy.html"><i class="fa-lock"></i> <span>Privacy Policy</span></a></li>
					<li class="nav-rate-update-app"><a href="#rate-our-app" class="popup-inline"><i class="fa-star"></i> <span>Rate Our App / Update App</span></a></li>
					<li class="nav-logout"><a href="#"><i class="fa-sign-out"></i> <span>LOGOUT</span></a></li>
				</ul>
				<div class="add-nav-sec">
					<a href="#" class="ckgs-logo"><img src="resources/images/common/retina/ckgs-white-logo.png" alt=""></a>
					<span>v 1.0.0</span>
				</div>
			</nav>
    	</div>
	<!-- Navigation bar ends -->
	
	<div class="container">
		<div class="ckgs-logo-container">
			<a href="#" class="ckgs-logo"><img src="resources/images/common/ckgs-logo-sm.png" alt=""></a>
			<div class="tagline">
				<label>Official Partner of Embassy of India Passport</label><b>IN USA</b>
			</div>
		</div>
		<div class="app-options">
			<a class="app-btns notification" href="javascript:void(0)"><i class="fa-bell"></i></a>
		</div>
	</div>
    <div class="overlay-bg"></div>
</header>
